#!/usr/bin/env python3
"""Regenerate the manuscript figures that have in-repo generators.

Currently wired: **Figure 2 (LACS)**. Its two halves are produced by
``trizod.figures.fig2_lacs`` (4-panel effect, from the cached comparison
pickle) and ``trizod.figures.fig2_lacs_case_study`` (alpha-synuclein + top
G-score flippers). Other main figures (Fig 1/3/4, supplementary) do not yet
have in-repo generators and are regenerated by hand.

Prerequisites (the script fails loudly if any is missing):
  fig2_lacs        : tmp/lacs_comparison_results.pkl  (build via
                     ``scripts/figures/compare_gscores_lacs.py --compute``)
                     + data/baseline/<tier>.json
  fig2_case_study  : tmp/bmrb_entries/ (BMRB pickle cache, populated by a
                     pipeline run) + data/baseline/tolerant.json

Writes into the manuscript Figures directory (default
``publication/manuscript/Figures/``); override with ``--output-dir`` to write
elsewhere (e.g. a scratch directory when verifying).

Usage:
    uv run python scripts/figures/regenerate_manuscript_figures.py
    uv run python scripts/figures/regenerate_manuscript_figures.py \
        --output-dir /tmp/figs --figures fig2_lacs
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from trizod.figures.fig2_lacs import plot_lacs_effect
from trizod.figures.fig2_lacs_case_study import build_case_study_figure

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_DIR = ROOT / "publication" / "manuscript" / "Figures"

ALL_FIGURES = ("fig2_lacs", "fig2_case_study")


def _require(path, hint):
    """Exit with a clear message if a prerequisite input is missing."""
    if not Path(path).exists():
        sys.exit(f"ERROR: missing prerequisite {path}\n  -> {hint}")


def regen_fig2_lacs(root: Path, out_dir: Path):
    pkl = root / "tmp" / "lacs_comparison_results.pkl"
    baseline = root / "data" / "baseline"
    _require(
        pkl,
        "build it: uv run python scripts/figures/compare_gscores_lacs.py --compute",
    )
    _require(
        baseline / "unfiltered.json", "per-tier baselines expected under data/baseline/"
    )
    print("[fig2_lacs] regenerating LACS 4-panel effect ...")
    plot_lacs_effect(
        pkl_path=pkl,
        baseline_dir=baseline,
        out_dir=out_dir,
        data_out_dir=out_dir,
    )


def regen_fig2_case_study(root: Path, out_dir: Path, max_scan: int):
    bmrb_cache = root / "tmp" / "bmrb_entries"
    baseline_tolerant = root / "data" / "baseline" / "tolerant.json"
    _require(bmrb_cache, "populate the BMRB pickle cache with a pipeline run first")
    _require(baseline_tolerant, "per-tier baselines expected under data/baseline/")
    print("[fig2_case_study] regenerating alpha-synuclein + flippers ...")
    build_case_study_figure(
        output=out_dir / "fig2_lacs_case_study.png",
        baseline_tolerant=baseline_tolerant,
        bmrb_cache=bmrb_cache,
        potenci_cache=root / "tmp",
        max_scan=max_scan,
    )


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory the figures are written to (default: manuscript Figures/).",
    )
    parser.add_argument(
        "--data-root",
        type=Path,
        default=ROOT,
        help="Repository root holding tmp/ and data/ (default: this repo).",
    )
    parser.add_argument(
        "--figures",
        default=",".join(ALL_FIGURES),
        help="Comma-separated subset of: " + ", ".join(ALL_FIGURES),
    )
    parser.add_argument(
        "--max-scan",
        type=int,
        default=200,
        help="Flipper-ranking scan bound for the case study (0 = full tolerant tier).",
    )
    args = parser.parse_args()

    selected = [f.strip() for f in args.figures.split(",") if f.strip()]
    unknown = [f for f in selected if f not in ALL_FIGURES]
    if unknown:
        sys.exit(f"ERROR: unknown figure(s) {unknown}; choose from {list(ALL_FIGURES)}")

    out_dir = args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    if "fig2_lacs" in selected:
        regen_fig2_lacs(args.data_root, out_dir)
    if "fig2_case_study" in selected:
        regen_fig2_case_study(args.data_root, out_dir, args.max_scan)

    print(f"Done. Figures written to {out_dir}")


if __name__ == "__main__":
    main()
